### ISSUE TITLE
Hi!!thx for your share!can you tell me what font you use in this picture?thx ag.

### ISSUE THREAD

**Issue by luobozz** [ceciljacob/code-plus-theme#1]
[https://github.com/ceciljacob/code-plus-theme/raw/master/image/theme-dark-blue-theme-screenshot.png](url)

**Comment by ghost** [comment]
Hi
he is use fira code font [repo](https://github.com/tonsky/FiraCode)

**Comment by luobozz** [comment]
thx for your reply,
I already use it:)

**Comment by ceciljacob** [comment]
The font used in the screenshot is available from this repository page :

**Fira Code**
[https://github.com/tonsky/firacode/releases](https://github.com/tonsky/firacode/releases)

-----

These are the font related settings in the `settings.json` file :

```
{
...
"editor.fontFamily": "'Fira Code'",
"editor.fontWeight": "500",
"editor.fontSize": 14,
"editor.fontLigatures": true,
...
}
```
